# Generated by Django 4.0.2 on 2022-02-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_user_transactions_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
